### PR TITLE
Add github pull request notifications

### PR DESCRIPTION
**Pull request by AndrewVos**

### CODE REVIEW

**Comment by issyl0** [comment]
If you haven't seen it in other Slack channels, there's also the Seal for this purpose - https://github.com/binaryberry/seal - made by our very own @binaryberry. How is this different?

**Comment by tijmenb** [comment]
Cool. How is it turned on / configured?

**Comment by AndrewVos** [comment]
@tijmenb I'll add it to the README, but https://github.com/hubot-scripts/hubot-github-repo-event-notifier/blob/master/src/github-repo-event-notifier.coffee#L8-L15

**Comment by tijmenb** [comment]
:+1:

**Comment by tijmenb** [comment]
This repo is auto-deployed, so the changes should be on Heroku in a couple of minutes.

**Comment by AndrewVos** [comment]
@issyl0 this is different cause it accepts hooks and immdiately writes them to the channel. Not sure if seal does that. Also, I had no idea `seal` existed :)

**Comment by binaryberry** [comment]
Thanks for evangelising the seal @issyl0 ! @AndrewVos : the Seal produces a report of all the existing pull requests that are open for specified users (your team). It gets run every morning at 9.30am, and the seal flags pull requests that have not been reviewed for 2 days or more by posting as an angry seal. 
So the seal is less noisy than this, it's "all PRs as of now" once a day as opposed to posting to slack as PRs are opened. You can checkout #custom or #core-formats on Slack at 9:30am if you'd like to see what it's like, and if you think it would be a useful complement to this, happy to help you set it up!

**Pull request merged**
