### PR TITLE
Make Hubot check for gem vulnerabilities

### PR DESCRIPTION
**Pull request by tijmenb**
This is a quick experiment to see if it helps with keeping our software current. If it seems useful and doesn't report too many false positives, we can rework it for use by other teams as well.

---

[govuk_security_audit](https://github.com/alphagov/govuk_security_audit) is a cool gem that wraps [bundler-audit](https://github.com/rubysec/bundler-audit). It allows us to check ruby repositories very easily for known security vulnerabilities. This will inspect the `Gemfile` of panopticon on GitHub master:

```
govuk_security_audit github alphagov panopticon
```

This Hubot plugin:
- Adds a command `hubot audit` to run this check against all repos owned by team Finding Things using `govuk_security_audit`.
- Automates this by running the audit every morning at 8AM.
### Deployment

To make the ruby available, we have to add the `heroku/ruby` buildpack first:

```
heroku buildpacks:add --index 1 heroku/ruby
```
### Screens

If all is okay:

screen shot 2016-02-05 at 15 43 34

If there are vulnerabilities Hubot will print them out:

screen shot 2016-02-05 at 15 47 08

screen shot 2016-02-05 at 15 46 53

### CODE REVIEW

**Comment by Davidslv** [comment]
looks awesome to me, but I'm biased on this :smile:

**Comment by tijmenb** [comment]
Hold off on merging this. Once https://github.com/alphagov/govuk_security_audit/pull/10 has been merged we can add panopticon again (and ignore the specific vulnerability).

**Comment by tijmenb** [comment]
Updated script to also check Panopticon, ignoring a specific vulnerability. Thanks to https://github.com/alphagov/govuk_security_audit/pull/10 and https://github.com/alphagov/govuk_security_audit/pull/11.

@Davidslv

**Comment by Davidslv** [comment]
:+1:

**Pull request merged**
