### PR TITLE
Don't announce audit every day

### PR DESCRIPTION
**Pull request by tijmenb**
Hubot currently announces every morning that it has run the security audit. While we appreciate Hubots faithful service and daily participation in the standup, this message has become a little repetitive.

### CODE REVIEW

**Comment by Davidslv** [comment]
I will let someone else merge :+1:

**Comment by tijmenb** [comment]
Why?

**Comment by Davidslv** [comment]
Someone can be interested in still see the message on Slack.

**Comment by tijmenb** [comment]
Allright then. This particular bot is only active on the slack channel of @alphagov/team-finding-things.

**Pull request merged**
